"""Pattern for ST-03 — back-cover HARD CTA (Plan B rebuild, P-12).

DATA-PREP ONLY. This module reads the package `page` dict, builds the QR SVG,
picks a geometric-overlay variant, shapes a context dict, and renders
`templates/st_03.html.jinja` (which composes the geo_shapes overlay + the
url_band + qr macros on a token-themed FULL-BLEED saturated-ground layout,
`styles/st_03.css`). The returned PageFragment.html is that rendered string; the
.css is the layout sheet's contents.

WHY this shape (vs the old hand-built f-string dark_cta_panel):
  - Brand-agnostic by construction: the template + layout CSS contain ZERO
    client literals (no hex, no font family, no client name). Colors + fonts
    arrive at render time via the token `:root` (compile_tokens) — the headline
    sizes off `var(--font-display)` (serif via the axis), the OVERSIZED URL off
    `var(--type-display-xl)` (the biggest type on the page).
  - The back cover is a CONFIDENT closing page and an AUTHORITY panel (DNA §C3,
    gap #4): a SOLID DARK --color-ink ground bleeding edge-to-edge via the SAME
    full-bleed technique the cover + breathing pages use (the suppressed named
    `@page bleed`, declared in the shared head), with a low-opacity token-colored
    geometric overlay (geo_shapes), a short headline, an OVERSIZED URL as the hero
    CTA (url_band --on-ground), and a QR (white box) beside the wordmark. The dark
    ink ground (not a saturated --color-primary) reads as a strong authority block
    for ANY brand — a tonal/mid-hue primary (e.g. apex's mid-cyan) would go pale,
    which is exactly the soft look this fix removes.

  Legibility: the oversized URL + headline read in --color-on-dark (white) on the
  dark ink ground — high-contrast for ANY brand, so the back cover reads as a
  strong, legible CTA universally.

DATA CONTRACT (preserved from the prior pattern — fields on page["data"]):
  title (the headline), body (a short supporting line), cta_text (an optional
  uppercase kicker above the URL), cta_url (the oversized URL — the hero). The
  URL falls back to brand.qr_target_url / brand.company_url_display so the back
  cover always carries a scannable CTA. The QR encodes the same target URL.

Body fields go through preprocess.preprocess_body (markdown → HTML). The QR is
generated by patterns._components.qr_svg (shared impl).

FULL-BLEED: the back-cover section assigns itself the suppressed named `@page
bleed` (margin:0, header band + folio removed) via `.page.st-03 { page: bleed }`
in styles/st_03.css. The named page itself is declared in the shared head
(assembler.shared_head_css) — @page rules cannot live in a fragment.

History (Plan B): replaced the prior dark_cta_panel render (hand-written .dcp CSS
with hardcoded color + font-family literals + an accent URL on a content-hugging
.dcp box) with this data-prep → Jinja-template split + a true full-bleed saturated
back cover (the cover's named-page technique) + the geo overlay + the oversized
on-dark url_band. Earlier history documented in git.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Allow flat imports from the chassis package.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from preprocess import preprocess_body  # noqa: E402
from templating import get_env  # noqa: E402
from patterns.base import PageFragment, RenderContext  # noqa: E402
from patterns._components import qr_svg as _qr_svg  # noqa: E402 — shared QR impl (DRY)

# Layout CSS lives in a sibling sheet so it's auditable by the brand-agnostic
# guard (tokens only). Read once at import; returned verbatim as fragment.css.
_CSS_PATH = Path(__file__).resolve().parent.parent / "styles" / "st_03.css"
_CSS = _CSS_PATH.read_text(encoding="utf-8")

# Content label for this report TYPE (not client-specific). The eyebrow that
# frames the closing CTA above the headline.
_EYEBROW = "Der nächste Schritt"

# Three geo-overlay arrangements (same as the breathing page); pick one off a
# stable page integer so the back cover's motif differs from the breathing pages.
_NUM_VARIANTS = 3


def _variant(page: dict) -> int:
    """Pick a geo-overlay variant (1..N) from a stable page integer (page/slot)."""
    raw = page.get("page_numbers") or page.get("slot") or 1
    try:
        n = int(str(raw).split("-")[0].strip())
    except (TypeError, ValueError):
        n = 1
    return (n - 1) % _NUM_VARIANTS + 1


def _display_url(u: str) -> str:
    """The DISPLAY form of the CTA URL: the bare domain, scheme + trailing slash
    stripped (Richard's closings show "apex-consulting.ai", never "https://…/").
    The QR still encodes the FULL target URL — only the printed text is cleaned."""
    s = (u or "").strip()
    for scheme in ("https://", "http://"):
        if s.lower().startswith(scheme):
            s = s[len(scheme):]
            break
    return s.rstrip("/")


def render(page: dict, ctx: RenderContext) -> PageFragment:
    """Render the ST-03 back-cover CTA page as a PageFragment.

    Data-prep → render templates/st_03.html.jinja. The full-bleed named `@page
    bleed` lives in the shared head (assembler); this returns only the page body
    markup + the ST-03-scoped layout CSS.
    """
    brand = ctx.brand
    d: dict = page.get("data") or {}

    # The oversized URL (the hero) + the QR target: the page's own cta_url, falling
    # back to the brand QR target / display URL so the back cover always closes
    # with a scannable CTA — never a blank hero.
    url = (d.get("cta_url") or brand.qr_target_url
           or brand.company_url_display or "").strip()
    qr_target = brand.qr_target_url or url

    # QR: DARK modules on a WHITE ground (the c-qr macro box is a white square),
    # so the code stays scannable over the saturated brand ground. The colours are
    # brand DATA, not literals — brand-agnostic.
    qr_markup = _qr_svg(
        url=qr_target,
        fg=brand.brand_neutral_dark,
        bg=brand.brand_neutral_light,
    ) if qr_target else ""

    # ATMOSPHERE ground: the brand's generated texture/gradient report asset as
    # the closing page's full-bleed material (the reference closers ground on a
    # rich dark texture, never flat navy). Graceful None -> plain ink ground.
    ground_uri = ctx.resolve_report_asset(
        ("background_texture", "atmospheric_gradient"),
        ("texture", "background", "gradient"),
    )

    template = get_env().get_template("st_03.html.jinja")
    html = template.render(
        # geo_shapes renders ONLY when no ground asset resolved (see the
        # template guard), so the variant pick is skipped entirely when a
        # ground is present: None documents "no overlay" instead of computing
        # a variant nothing will read.
        variant=None if ground_uri else _variant(page),
        eyebrow=_EYEBROW,
        headline=d.get("title", ""),
        body_html=preprocess_body(d.get("body", "")),
        cta_label=d.get("cta_text", ""),
        url=_display_url(url),
        qr_svg=qr_markup,
        wordmark=brand.company_name_short,
        ground_uri=ground_uri,
        # the ghost numeral = the back-cover page number (the deck's recurring
        # oversized-section-number device — fills the quiet top deliberately).
        ghost_number=str(page.get("page_numbers") or page.get("slot") or 20),
    )
    return PageFragment(html=html, css=_CSS)
