"""Pattern for ST-07A — Case Study (Plan B flagship rebuild).

DATA-PREP ONLY. This module reads the package `page` dict, builds the QR
SVG, resolves the portrait URI, shapes a context dict, and renders
`templates/st_07a.html.jinja` (which composes the atomic macro library on a
token-themed layout, `styles/st_07a.css`). The returned PageFragment.html is
that rendered string; the .css is the layout sheet's contents.

WHY this shape (vs the old hand-built f-string CSS):
  - Brand-agnostic by construction: the template + layout CSS contain ZERO
    client literals (no hex, no font family, no client name). Colors + fonts
    arrive at render time via the token `:root` (compile_tokens) — the headline
    sizes off `var(--font-display)`, which resolves to the SERIF face when the
    brand's axis is headline_type=serif (the apex deck IS serif).
  - The component LOOK (pill / stat-strip / pull-quote / qr / section-label /
    media) lives in styles/components.css (already in the shared <head>); this
    pattern only feeds the macros DATA and positions them.

DATA CONTRACT (fields on page["data"]):
  kurzportraet, ausgangsproblem, ziel, loesung, ergebnis_text,
  ergebnis_headline, fallstudie_number, pullquote.{text,attribution},
  kunde.{name,company_url} (+ optional funktion = role),
  ergebnis_metrics[] (list of {label,value} dicts OR "label: value" strings).
  Plus brand.qr_target_url, brand.company_url_display.

CLIENT PORTRAIT — v2.0 `slots[]` (DNA §C2, the FIXED case-study photo slot):
  ctx.slot_uri(page, "case_study_portrait") (the single-photo primitive).
  - RESOLVED (e.g. apex Fallstudie 3 / Frese) → a LARGE framed portrait at the top
    of the sidebar (DNA §C2: a named client face, full-color, never tiny) beside
    name/role/own-URL + QR.
  - ABSENT (the other apex case studies, status "missing_required") → the template
    renders NO photo AND NO empty placeholder box (an explicit OWNER decision: a
    missing case-study photo must render beautifully WITHOUT a frame, never an
    empty grey plate). The sidebar reflows cleanly to the name/role/url block + the
    QR/pull-quote panel. This closes DNA gap #3 (empty case-study photo boxes).

Body fields go through preprocess.preprocess_body (markdown → HTML). The QR is
generated by patterns._components.qr_svg (shared impl).

NON-EMPTY-SECTION LOGIC (preserved): a body section is emitted ONLY when its
content is non-empty. Some case studies have an empty `ziel` (WENDEPUNKT
absent); rendering an empty section wastes vertical space and can push the
longest case study onto a 2nd physical page.

The German section headings (Ausgangssituation / Ziel / Lösung / Ergebnis) and
the FALLSTUDIE kicker are CONTENT labels for this report type — defined as
module constants here (not scattered, not client-specific) and passed to the
template as data.

History (Plan B): replaced the prior monolithic f-string render (hand-written
.lrp-grid CSS with hardcoded color + font-family literals baked into the
pattern) with this data-prep → Jinja-template split. Grammar required-present checks +
chassis_config keep-alive retained. Earlier history (Move 2c, design_preferences
deletion, CoralValidator→AccentBudgetValidator) documented in git.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Allow flat imports from the chassis package.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import chassis_config  # noqa: E402 — kept for future pattern needs (CTA box etc.)
from preprocess import preprocess_body  # noqa: E402
from templating import get_env, _leadnum  # noqa: E402
from patterns.base import PageFragment, RenderContext  # noqa: E402

# Layout CSS lives in a sibling sheet so it's auditable by the brand-agnostic
# guard (tokens only). Read once at import; returned verbatim as fragment.css.
_CSS_PATH = Path(__file__).resolve().parent.parent / "styles" / "st_07a.css"
_CSS = _CSS_PATH.read_text(encoding="utf-8")

# Content labels for this report TYPE (not client-specific). Section order is
# fixed: Ausgangssituation → Ziel → Lösung → Ergebnis. Each pairs the German
# heading with the page-data field that feeds it.
_SECTION_SPEC: tuple[tuple[str, str], ...] = (
    ("Ausgangssituation", "ausgangsproblem"),
    ("Ziel", "ziel"),
    ("Lösung", "loesung"),
    ("Ergebnis", "ergebnis_text"),
)
_KICKER_BASE = "FALLSTUDIE"

# Max charts rendered on a case-study page — keeps the chart band ONE side-by-side
# row that fills the dead bottom band without overflowing onto a spill page.
CS_MAX_CHARTS = 2


def _is_long_value(value: str) -> bool:
    """Classify a stat value as "prose/long" (True) vs "numeral-like" (False).

    Used ONLY by the fill variant: a "prose" value gets a `--long` CSS modifier
    that steps the font size DOWN so a multi-word phrase WRAPS cleanly inside
    the narrow dark panel instead of overflowing/clipping at the oversized
    --type-display-xl numeral size. A "numeral-like" value keeps the big size.

    This is FORMAT classification, not brand logic — no client literals, no
    colours, no fonts; it inspects only the value's shape.

    Heuristic (kept deliberately simple + documented):
      A value is "numeral-like" (stays BIG) when it is a compact figure: at most
      THREE WORD tokens (a "word token" carries a letter or digit; pure
      separators like "→", "-", ">", "€" don't count) AND at least one digit,
      where every alphabetic token is a short unit/connector (<= 7 chars). This
      keeps crisp metrics big — "4", "> 200.000 €", "24 Std. → Minuten" (3 word
      tokens: 24 / Std. / Minuten; the arrow is a separator; "Std."/"Minuten"
      are short). Everything else — long phrases, many words, or word-dominant
      text with no figure — is "prose" (shrinks): "von bis zu 24 Stunden auf
      Minuten" (6 word tokens), "tausende WhatsApp-Chats automatisiert" (long
      word tokens; "WhatsApp-Chats" is 14 chars), "0 neue Mitarbeiter"
      ("Mitarbeiter" is 11 chars).

    The hard requirement is FITTING (no clip); staying maximally-big is the
    nice-to-have. When in doubt the heuristic prefers shrinking (wrap-safe).
    """
    v = (value or "").strip()
    if not v:
        return False
    # word tokens carry at least one letter or digit; pure-separator tokens
    # (arrows, dashes, ">", currency glyphs) are ignored for the count.
    word_tokens = [t for t in v.split() if any(ch.isalnum() for ch in t)]
    if len(word_tokens) > 3:
        return True  # multi-word phrase → prose
    has_digit = any(ch.isdigit() for ch in v)
    if not has_digit:
        return True  # word-only label-like value → prose (no compact figure)
    # has a figure and <= 3 word tokens: stays big ONLY if every alphabetic
    # token is a short unit/connector. A long alphabetic token
    # ("WhatsApp-Chats", "Mitarbeiter", "automatisiert") means the value is
    # really a phrase that happens to contain a digit → prose so it wraps.
    for tok in word_tokens:
        if any(ch.isalpha() for ch in tok) and len(tok) > 7:
            return True
    return False


def _transform_bar_heights(frm: str, to: str) -> tuple[int, int]:
    """Bar heights (% of the track) for a before->after transform cell.

    The geometry derives from the SAME leading-number extractor the viz macros
    use (`_leadnum`), so the rail's before/after bars and the page-body
    before/after bars size a value identically. The taller bar is the larger
    magnitude; a side with NO number (e.g. the qualitative "Minuten") floors to
    a small visible sliver so the picture reads "drastically reduced" WITHOUT
    inventing a figure. FORMAT geometry only — never client text, never a
    fabricated number. "24 Std." vs "Minuten" → (100, sliver); "30 Min" vs
    "2 Min" → (100, ~12).
    """
    fn, tn = _leadnum(frm), _leadnum(to)
    m = max(fn, tn)
    floor = 12  # smallest visible bar so a near-zero / no-number state still shows
    if m <= 0:
        return 100, floor
    return max(round(fn / m * 100), floor), max(round(tn / m * 100), floor)


def render(page: dict, ctx: RenderContext) -> PageFragment:
    """Render the ST-07A case-study page as a PageFragment.

    Data-prep → render templates/st_07a.html.jinja. Head-level CSS
    (@page/@font-face/:root/body + the component `c-` classes) lives in the
    shared head (assembler); this returns only the page body markup + the
    ST-07A-scoped layout CSS.
    """
    brand = ctx.brand
    grammar = ctx.grammar
    d: dict = page.get("data") or {}

    # ---- grammar required-present checks (FAIL LOUD) ----
    grammar.get_section("3.5")   # color discipline
    grammar.get_section("2")     # P-6 case study
    grammar.get_section("3.7")   # accent firing locations
    grammar.get_section("4.0")   # type axes

    _ = chassis_config  # kept live for future per-element-class calls

    # ---- QR: case studies render NO QR. A scannable code mid-case-study reads as
    # clutter (it never points anywhere a reader scans here); the SINGLE designed
    # QR lives on the back-cover CTA page (ST-03). The template stays QR-capable
    # (qr_svg guard) — this pattern simply feeds it nothing. ----

    # ---- client portrait from the v2.0 slots[] (DNA §C2 — the FIXED case-study
    # photo slot). The single-photo primitive: resolved → a file URI for a LARGE
    # framed portrait; None → '' so the template renders NO photo AND NO empty
    # placeholder box (owner decision: a missing case-study photo must render
    # beautifully WITHOUT a frame; the sidebar reflows to name/role/url + QR). ----
    portrait_uri = ctx.slot_uri(page, "case_study_portrait") or ""

    # ---- OPTIONAL supporting SCENE for the A3 spread (the "visual that fills
    # the void bands" device): a generated brand-toned abstract scene
    # (case_scene slot — fal pipeline output, never a face, never fake data)
    # renders as a full-bleed rounded band INSIDE the left narrative column,
    # between the sections. Absent -> no markup (graceful: a client without a
    # US-505 (Richard grammar): the abstract fal "scene" bands are REMOVED.
    # Richard NEVER uses abstract generative art — his case-study spreads use
    # data devices (the right proof panel) + real photography. The abstract
    # waves were flagged on p7/p9/p14/p15 as "generic, meaningless, zero data".
    # US-503 measure-fit: a DENSE spread (narrative > 1300 chars, e.g. Frese)
    # cannot hold kicker+headline+portrait+lede+3 sections on the 260mm sheet
    # at the roomier measure. The LEDE is suppressed on dense spreads —
    # Richard's case-study spreads lead with the narrative; the portrait +
    # headline carry the intro.
    _narr_only = sum(
        len(str(d.get(field) or "")) for _, field in _SECTION_SPEC
        if field != "ziel"
    )
    lede_html = preprocess_body(d.get("kurzportraet", ""))
    if _narr_only > 1300:
        lede_html = ""
    scene_uri = ""

    # ---- OPTIONAL client-matched social post (DNA §C2 "live social presence";
    # the Social Layout Planner's `case_study_post` binding). When the page
    # carries `data.social_post` (a real client-matched IG post: {photo, avatar?,
    # handle}), it can render as a COMPACT renderer-drawn phone_mockup in the
    # portrait slot's position. The rail is narrow, so only ONE photo occupies it
    # (never two stacked — that overflows). Never fabricates engagement: only the
    # supplied real photo/avatar/handle show. ----
    social = d.get("social_post") or {}

    def _res(rel: str) -> str:
        if not rel:
            return ""
        p = ctx.resolve_asset(str(rel))
        return p.as_uri() if p is not None else ""

    social_photo = _res(social.get("photo", ""))
    social_avatar = _res(social.get("avatar", ""))
    social_handle = str(social.get("handle", "")).strip()
    # PRIORITY: a REAL resolved client PORTRAIT is the authority photo and always
    # wins the rail (DNA §C2 — a named client face). The social_post phone is
    # secondary: it only takes the rail when there is NO real portrait to show
    # (so a portrait-less case study with a matched post still gets a live-social
    # visual). Showing both would stack two photos in the narrow rail and
    # overflow, so the phone is suppressed whenever the portrait is present. This
    # is the inverse of the prior rule (which blanked the real photo). Graceful:
    # pages with NEITHER portrait NOR social_post (Fallstudie 1/2/4/5) render no
    # photo and no empty box, exactly as before.
    has_social_post = bool(social_photo) and not portrait_uri

    # ---- body sections: emit ONLY non-empty ones (preserved logic) ----
    sections: list[dict[str, str]] = []
    for heading, field in _SECTION_SPEC:
        body_html = preprocess_body(d.get(field, ""))
        if body_html.strip():
            sections.append({"heading": heading, "body_html": body_html})

    # ---- ergebnis_metrics → stat_strip stats (dicts OR "label: value" strings) ----
    stats: list[dict[str, object]] = []
    for m in (d.get("ergebnis_metrics") or []):
        if isinstance(m, dict):
            label, value = m.get("label", ""), m.get("value", "")
        elif isinstance(m, str) and ":" in m:
            label, value = (s.strip() for s in m.split(":", 1))
        else:
            label, value = "", str(m)
        if not (label or value):
            continue
        value = str(value).strip()
        # US-504 (German grammar): a metric that starts lowercase ("von bis zu
        # 24 Stunden auf Minuten") reads as a sloppy typo in a KPI slot. The
        # KPI displays the raw value, so sentence-case its first letter here
        # (FORMAT only — never touches digits, % or unit content).
        if value and value[0].islower():
            value = value[0].upper() + value[1:]
        # keep a trailing currency glyph and a leading comparator hugging the
        # figure (non-breaking) so a wide value like "> 200.000 €" never strands
        # the "€" or ">" on its own line in the narrow rail. FORMAT spacing only.
        value = value.replace(" €", " €")  # currency hugs the number
        # a leading comparator (">"/"<") renders as a SMALL prefix so the
        # number stays the hero and the figure ("200.000 €") fits the rail.
        cmp = ""
        if value[:1] in "<>":
            cmp, value = value[0], value[1:].lstrip()
        # `is_long` (FORMAT logic, not brand): a "prose" value would OVERFLOW the
        # narrow fill panel at the oversized numeral size; the fill template's
        # `--long` modifier steps it DOWN so it wraps. Crisp numerals stay big.
        stat: dict[str, object] = {
            "kind": "figure", "label": label,
            "value": value, "is_long": _is_long_value(value),
            "cmp": cmp,
        }
        # A before->after TRANSFORMATION expressed as "FROM → TO" (e.g.
        # "24 Std. → Minuten") renders badly as one oversized numeral with a
        # stray arrow. Emit a structured transform cell so the fill rail draws a
        # proper high-contrast before->after DEVICE instead. `value` is retained
        # (the full string) so the STANDARD variant's stat_strip still renders.
        # FORMAT logic only (separator glyphs), never client text.
        sep = "→" if "→" in value else ("->" if "->" in value else None)
        if sep:
            frm, _, to = value.partition(sep)
            frm, to = frm.strip(), to.strip()
            # US-504 (German grammar): a lowercase-start phrase in a metric
            # slot ("von bis zu 24 Stunden...", "von fragmentiert auf...")
            # reads as a sloppy typo — the audit flagged p12/p15. Sentence-
            # case the phrase side (FORMAT only: capitalizes the first letter,
            # never touches the content). Digits/%/units are untouched.
            def _de_case(s: str) -> str:
                if s and s[0].islower():
                    return s[0].upper() + s[1:]
                return s
            frm, to = _de_case(frm), _de_case(to)
            from_h, to_h = _transform_bar_heights(frm, to)
            stat.update({
                "kind": "transform", "from": frm, "to": to,
                "from_h": from_h, "to_h": to_h,
            })
        stats.append(stat)

    # ---- structured fields ----
    fallstudie_number = d.get("fallstudie_number", "")
    kicker_label = (
        f"{_KICKER_BASE} 0{fallstudie_number}" if fallstudie_number else _KICKER_BASE
    )
    kunde = d.get("kunde") or {}
    kunde_url = kunde.get("company_url", "") or brand.company_url_display
    # href needs a scheme; the displayed text stays the bare domain.
    kunde_href = kunde_url if "://" in kunde_url else f"https://{kunde_url}"
    pullquote = d.get("pullquote") or {}

    # ---- layout variant (per-page hint) ----------------------------------
    # "standard" (DEFAULT, unchanged): wide MAIN column on the right + a ~31%
    #   sidebar on the left (portrait/name/url + a small QR/quote panel). This
    #   under-fills a short case study (dead bottom band).
    # "fill": the expert "authority panel" composition (niklas p8/p10/p12) — a
    #   FULL-HEIGHT dark sidebar on the RIGHT (portrait-if-present → name/role/
    #   url-in-accent → a VERTICAL big-number stat STACK → QR + pull-quote at the
    #   bottom) that runs edge-to-edge top→bottom regardless of body length, with
    #   the body sections flowing in the wider LEFT column. The full-height dark
    #   panel is what kills the dead space. Brand-agnostic: tokens only.
    # "spread_story" / "spread_proof": the BREATHING two-page spread (the layout
    #   redesign). spread_story is the narrative alone on a generous page (no
    #   sidebar, distributed whitespace, clean section units); spread_proof is the
    #   facing page where the data-viz is the HERO on a COMPOSED ground (never a
    #   blank page), with one supporting stat + the pull-quote and real margins.
    layout_variant = page.get("layout_variant", "standard")
    if layout_variant not in ("standard", "fill", "spread_story", "spread_proof", "magazine", "casestudy_hero"):
        layout_variant = "standard"

    # ---- data-driven chart SVG(s): the pre-processor extracts chart specs onto
    # page["charts"] and appends a brand-styled SVG per spec to page["components"]
    # (the tail). Embedded in the main column's chart/stat region; absent → []
    # so the page renders exactly as before (graceful, chart-less unchanged). ----
    # Cap at CS_MAX_CHARTS so the chart band stays ONE row (side-by-side) that
    # fits the case-study dead bottom band without overflowing to a spill page.
    chart_svgs = ctx.chart_svgs(page)[:CS_MAX_CHARTS]

    # data-viz PRESET layer: data['viz'] is a list of {preset, …} specs the
    # curation step wrote (verbatim figures). Coerce to None unless a non-empty
    # list so the template renders exactly as before when absent (graceful). The
    # template renders the dispatch in a full-width cs-viz band in the dead
    # bottom region — complements, not duplicates, the numeric stat strip.
    viz = d.get("viz")
    viz = viz if isinstance(viz, list) and viz else None

    # The casestudy_hero "Das Ergebnis" dashboard is a floating DARK ISLAND panel
    # (Richard's depth device, the rep_statcard/canvas_bi_dashboard treatment): it
    # grounds on --color-ink and is faced with the AI navy-STONE material so the
    # proof reads as a textured dimensional surface, not a flat chip. Resolved from
    # the package-level panel_texture report asset (graceful → token navy when the
    # package carries none). Renderer-owned placement; brand-agnostic.
    panel_texture_uri = ctx.resolve_report_asset(
        ("panel_texture",), ("panel_texture",)
    ) or ""

    template = get_env().get_template("st_07a.html.jinja")
    html = template.render(
        layout_variant=layout_variant,
        chart_svgs=chart_svgs,
        viz=viz,
        panel_texture_uri=panel_texture_uri,
        kicker_label=kicker_label,
        # The bare Fallstudie number drives the decorative ghost numeral (a faint
        # oversized digit behind the kicker, DNA §C1/§C6). Falsy → no ghost.
        fallstudie_number=fallstudie_number,
        headline=d.get("ergebnis_headline", ""),
        lede_html=lede_html,
        portrait_uri=portrait_uri,
        portrait_alt=kunde.get("name", ""),
        scene_uri=scene_uri,
        has_social_post=has_social_post,
        social_photo=social_photo,
        social_avatar=social_avatar,
        social_handle=social_handle,
        kunde_name=kunde.get("name", ""),
        kunde_role=kunde.get("funktion", ""),
        kunde_url=kunde_url,
        kunde_href=kunde_href,
        qr_svg="",
        pullquote_text=preprocess_body(pullquote.get("text", "")),
        pullquote_attribution=pullquote.get("attribution", ""),
        stats=stats,
        sections=sections,
    )
    return PageFragment(html=html, css=_CSS)
